### ISSUE TITLE
make compile error

### ISSUE THREAD

**Issue by LeonardooAlves** [CTSRD-CHERI/Piccolo#10]
Error while regenerating the SSITH P1 core files:

Error: "src_BSV/P1_Core.bsv", line 256, column 24: (T0020)
  Type error at:
    core.cpu_imem_master

  Expected type:
    AXI4_Types::AXI4_Master_Synth#(TAdd#(Fabric_Defs::Wd_MId, 1),
			       Fabric_Defs::Wd_Addr,
			       Fabric_Defs::Wd_Data,
			       0,
			       0,
			       0,
			       0,
			       0)

  Inferred type:
    AXI4_Types::AXI4_Master_Synth#(Fabric_Defs::Wd_MId,
			       Fabric_Defs::Wd_Addr,
			       Fabric_Defs::Wd_Data,
			       0,
			       0,
			       0,
			       0,
			       0)

make: *** [Makefile:113: compile] Error 1

**Comment by jrtc27** [comment]
Fixed by b2103cfc8920590cb1e905ef545a842e8eb810e3, though are you sure you want to be using Piccolo?

**Comment by LeonardooAlves** [comment]
> Fixed by [b2103cf](https://github.com/CTSRD-CHERI/Piccolo/commit/b2103cfc8920590cb1e905ef545a842e8eb810e3), though are you sure you want to be using Piccolo?

Thank you. I want to check if it works, but my main goal is to use Flute.
