### ISSUE TITLE
simulations fail with the verilator build

### ISSUE THREAD

**Issue by tariqkurd-repo** [CTSRD-CHERI/Piccolo#13]
I've used verilator to build and run but all the tests fail, I did this:

`git clone --recursive https://github.com/CTSRD-CHERI/Piccolo.git`
`cd Piccolo/builds/`
`Resources/mkBuild_Dir.py  ..  RV32CIxCHERI verilator`
`cd RV32CIUxCHERI_Piccolo_verilator`
`make compile simulator test`

it builds fine, but there's a problem with the test. The test binary is the same as for the bluesim target where it executes without problems.

`Verilator 3.916 2017-11-25 rev verilator_3_914-65-g0478dbd`
Running on x86 linux Ubuntu 18.04

tariq@lhrptariq00002:/data/cores/Piccolo_verilator/Piccolo/builds/RV32CIUxCHERI_Piccolo_verilator$ make test
../../builds/Resources/Include_Common.mk:125: warning: overriding recipe for target 'tagsparams'
../../builds/Resources/Include_Common.mk:115: warning: ignoring old recipe for target 'tagsparams'
make -C  ../../Tests/elf_to_hex
make[1]: Entering directory '/data/cores/Piccolo_verilator/Piccolo/Tests/elf_to_hex'
make[1]: 'elf_to_hex' is up to date.
make[1]: Leaving directory '/data/cores/Piccolo_verilator/Piccolo/Tests/elf_to_hex'
../../Tests/elf_to_hex/elf_to_hex  ../../Tests/isa/rv32ui-p-add  Mem.hex
c_mem_load_elf: ../../Tests/isa/rv32ui-p-add is a 32-bit ELF file
Section .text.init      : addr         80000000 to addr         80000604; size 0x     604 (= 1540) bytes
Section .tohost         : addr         80001000 to addr         80001048; size 0x      48 (= 72) bytes
Section .riscv.attributes: Ignored
Section .symtab         : Searching for addresses of '_start', 'exit' and 'tohost' symbols
Writing symbols to:    symbol_table.txt
    No 'exit' label found
Section .strtab         : Ignored
Section .shstrtab       : Ignored
Min addr:                    80000000 (hex)
Max addr:                    80001047 (hex)
Writing mem hex to file 'Mem.hex'
Subtracting 0x80000000 base from addresses
./exe_HW_sim  +v1  +tohost
`%Error: Mem.hex:135: $readmem file ended before specified ending-address`
`Aborting...`
`../../builds/Resources/Include_Common.mk:96: recipe for target 'test' failed`
`make: *** [test] Aborted (core dumped)`

**Comment by PeterRugg** [comment]
Thanks for pointing this out. Looks like an issue with the elf-to-hex file, where the size of the memory initialisation files it's producing doesn't line up with what Piccolo is expecting. I'll take a look and hopefully push a fix today.

**Comment by PeterRugg** [comment]
Should be fixed with https://github.com/CTSRD-CHERI/Piccolo/commit/fae4b5db75099dc31dd641c0e94bcc744c3fac9f

**Comment by tariqkurd-repo** [comment]
Thanks so much, especially for the very quick response
