### ISSUE TITLE
Is there a toolchain available for Piccolo CHERI? And basic CHERI tests?

### ISSUE THREAD

**Issue by tariqkurd-repo** [CTSRD-CHERI/Piccolo#14]
Hi,

Is there a toolchain available for Piccolo CHERI? The only toolchain I've found is for RV64.
https://github.com/CTSRD-CHERI/cheribuild and we built `cheribuild.py [options] run-riscv64-purecap`

I wonder if it's possible to use this toolchain to build for the RV32 and if there are libraries available for linking with the Piccolo platform, so we can compile and run C programs on the Piccolo testbench.

Tariq

**Comment by PeterRugg** [comment]
Sorry for not noticing this earlier! I believe @heshamelmatary has been doing some work on the 32-bit toolchain, so it's possible he has an answer for this.

**Comment by heshamelmatary** [comment]
I do maintain a cheribuild branch for 32-bit stuff. It's mainly intended to support my 32-bit CheriFreeRTOS research, but that's very much WIP, I won't consider it a CHERI test. For more details check out this [README](https://github.com/CTSRD-CHERI/FreeRTOS-Demos-CHERI-RISC-V). You'd get 32-bit compiler-rt and newlib libc that FreeRTOS depends on if you follow instructions there (replacing riscv64 with riscv32)

**Comment by tariqkurd-repo** [comment]
Thanks, we've checked out the hkma2 branch
