### ISSUE TITLE
Duplicate address in the SoC_Map.bsv

### ISSUE THREAD

**Issue by LeonardooAlves** [CTSRD-CHERI/Piccolo#19]
Hi, I hope you are well.

I would like to highlight that the base address for UART 1 and SPI 0 (AXI Lite) are duplicated in the [src_SSITH_P1/src_BSV/SoC_Map.bsv](https://github.com/CTSRD-CHERI/Piccolo/blob/2e3132a98c0682e5ec50c9c8e7ad4c45325d5e35/src_SSITH_P1/src_BSV/SoC_Map.bsv#L203). I noticed that for both Piccolo and Flute repositories.

**Comment by jrtc27** [comment]
Hm, ours seems to have diverged a lot from upstream in terms of what devices there are defined and where (and I can't even find a time when there was a UART 1 upstream at that location). According to the Vivado project that SPI should be at 0x62400000 (without the 3). In practice it doesn't matter though, anything not memory is treated as I/O.

**Comment by LeonardooAlves** [comment]
Thanks for the clarification.
